

#include <ShlObj.h>
#include <algorithm>
#include <DirectXMath.h>
#include <memory>
#include <vector>
#include "vector.hpp"
#include "iniwriter.hpp"
#include "math.hpp"
#include "recvprop.hpp"
#include "netvars.hpp"
#include "offsets.hpp"
#include "weapon.hpp"
#include "enums.hpp"
#include "entities.hpp"
#include "surface.hpp"
#include "engineclient.hpp"
#include "materials.hpp"
#include "usercmd.hpp"
#include "enginetrace.hpp"
#include "interfaces.hpp"
#include "render.hpp"
#include "mouse.hpp"
#include "menu.hpp"
#include "visuals.hpp"
#include "aimbot.hpp"
#include "lagcomp.hpp"
#include "variables.hpp"
#include "draw.hpp"
#include "hooking.hpp"